[package]
name = "sui_oracle_market"
edition = "2024"

# TODO switch once [environments] added in dependencies
[dependencies]
[dependencies.pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "d809788e83087c69d76e4671cd694e88a189a179"

[dependencies.openzeppelin_math]
git = "https://github.com/OpenZeppelin/contracts-sui.git"
subdir = "math/core"
rev = "v0.1"

# [dependencies]

# # Oracle price feeds
# [dependencies.pyth]
# local = "../vendors/pyth"

# [dependencies.openzeppelin_math]
# local = "../vendors/openzeppelin-math"

# [dependencies.Sui]
# local = "../vendors/sui-framework"

# [dependencies.MoveStdlib]
# local = "../vendors/move-stdlib"


[environments]
localnet = "279218ea"

[dep-replacements.localnet]
pyth = { local = "../pyth-mock", override = true, rename-from = "Pyth" }
