[package]
name = "sui_oracle_market"
edition = "2024"

[dependencies]
[dependencies.pyth]
local = "../pyth-upstream-patched"

[environments]
localnet = "bace5cdf"
testnet_beta = "4c78adac"

[dep-replacements.localnet]
pyth = { local = "../pyth-mock", override = true, rename-from = "Pyth" }
